### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by mathiasbynens** [brettz9/es-identifiers#1]
E.g.

```js
> IdentifierName.test('\\u0000')
< true
```

**Comment by brettz9** [comment]
Ah yes, thanks for pointing that out. It wasn't sufficient to follow the grammar, as the text naturally also imposed limits on what those escapes resolve to: https://tc39.github.io/ecma262/#sec-names-and-keywords . I guess I may want to get at the hex values your regex mostly produces and incorporate them.

**Comment by brettz9** [comment]
Fixed in 9201a43c18ac37e3811aa0b94bc85267cd6308e4 . I decided against trying to include the escape sequences at all since JavaScript resolves them. Although there is a minor use case to have another regex that supports them (e.g., `<input pattern>` if allowing users to add Unicode escapes there), I'm not concerned enough to trouble with supporting it (and even something like `\\u0061` would be a false positive if the context was not doing any conversion of escapes.

Thanks again for the report!
